# Generated by Django 3.2.5 on 2022-04-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Makes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
                ('mileage', models.IntegerField()),
                ('comments', models.CharField(max_length=256)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autos.makes')),
            ],
        ),
    ]
